package com.example.sdemo;

import com.example.sdemo.entity.Participant;

rule "prize_invitees"
    no-loop true
    lock-on-active true
    salience 1
when
    $Participant : Participant(isInvitees == 1)
then
    $Participant.setPrizeDays(3);
    update($Participant);
end

rule "prize_1"
    no-loop true
    lock-on-active true
    salience 1
when
    $Participant : Participant(succeedCount>=1 && succeedCount<3);
then
    $Participant.setPrizeDays(5);
    update($Participant);
end

rule "prize_2"
    no-loop true
    lock-on-active true
    salience 1
when
    $Participant : Participant(succeedCount>=3 && succeedCount<5);
then
    $Participant.setPrizeDays(10);
    update($Participant);
end

rule "prize_3"
    no-loop true
    lock-on-active true
    salience 1
when
    $Participant : Participant(succeedCount>=5 && succeedCount<7)
then
    $Participant.setPrizeDays(20);
    update($Participant);
end

rule "prize_4"
    no-loop true
    lock-on-active true
    salience 1
when
    $Participant : Participant(succeedCount>=7 && succeedCount<10)
then
    $Participant.setPrizeDays(30);
    update($Participant);
end

rule "prize_5"
    no-loop true
    lock-on-active true
    salience 1
when
    $Participant : Participant(succeedCount>=10)
then
    $Participant.setPrizeDays(45);
    update($Participant);
end



